//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Levelkuldes.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Levelkuldes.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap AccountAttribute_16x {
            get {
                object obj = ResourceManager.GetObject("AccountAttribute_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Address_16x {
            get {
                object obj = ResourceManager.GetObject("Address_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap AddUserGroup_16x {
            get {
                object obj = ResourceManager.GetObject("AddUserGroup_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Címzettek betöltve..
        /// </summary>
        public static string CimzettekBetoltve {
            get {
                return ResourceManager.GetString("CimzettekBetoltve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CloseSolution_16x {
            get {
                object obj = ResourceManager.GetObject("CloseSolution_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap F1Help_16x {
            get {
                object obj = ResourceManager.GetObject("F1Help_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba a Cimzettek oldalon!.
        /// </summary>
        public static string HibaCimzettek {
            get {
                return ResourceManager.GetString("HibaCimzettek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba az Üzenet oldalon!.
        /// </summary>
        public static string HibaUzenet {
            get {
                return ResourceManager.GetString("HibaUzenet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adatok importálása szükséges..
        /// </summary>
        public static string ImportalasSzukseges {
            get {
                return ResourceManager.GetString("ImportalasSzukseges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A mező kitöltése kötelező..
        /// </summary>
        public static string KotelezoMezo {
            get {
                return ResourceManager.GetString("KotelezoMezo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levél betöltve..
        /// </summary>
        public static string LevelBetoltve {
            get {
                return ResourceManager.GetString("LevelBetoltve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levelek elküldve..
        /// </summary>
        public static string LevelekElkuldve {
            get {
                return ResourceManager.GetString("LevelekElkuldve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levelek küldése folyamatban....
        /// </summary>
        public static string LevelekKuldese {
            get {
                return ResourceManager.GetString("LevelekKuldese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Mail_16x {
            get {
                object obj = ResourceManager.GetObject("Mail_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nincs fájl kiválasztva..
        /// </summary>
        public static string NincsFajl {
            get {
                return ResourceManager.GetString("NincsFajl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ReceiveMail_16x {
            get {
                object obj = ResourceManager.GetObject("ReceiveMail_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SendTestMail_16x {
            get {
                object obj = ResourceManager.GetObject("SendTestMail_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
